"""initial

Revision ID: ad2c72d53211
Revises: 
Create Date: 2026-03-05 23:42:10.168645+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2c72d53211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nicho', sa.Text(), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('brand_identity', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('monitored_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('RESEARCHING', 'ORCHESTRATING', 'AWAITING_SELECTION', 'GENERATING_COPY', 'COPY_REVIEW', 'GENERATING_ART', 'ART_REVIEW', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', name='pipelinestate'), nullable=False),
    sa.Column('topic_selected', sa.String(length=36), nullable=True),
    sa.Column('channels_selected', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('social_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_social_tokens_user_platform')
    )
    with op.batch_alter_table('social_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('copies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('INSTAGRAM', 'LINKEDIN', 'TWITTER', 'YOUTUBE', 'EMAIL', name='copychannel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', name='copystatus'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copies_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('channels_found', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_user_id'), ['user_id'], unique=False)

    op.create_table('arts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('copy_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('STATIC', 'CAROUSEL', 'THUMBNAIL', name='arttype'), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arts_copy_id'), ['copy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arts_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('scheduled_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('copy_id', sa.String(length=36), nullable=False),
    sa.Column('art_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', name='scheduledpoststatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['arts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_posts_art_id'), ['art_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_copy_id'), ['copy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_copy_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_art_id'))

    op.drop_table('scheduled_posts')
    with op.batch_alter_table('arts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arts_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_arts_copy_id'))

    op.drop_table('arts')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_topics_pipeline_id'))

    op.drop_table('topics')
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copies_pipeline_id'))

    op.drop_table('copies')
    with op.batch_alter_table('social_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_tokens_user_id'))

    op.drop_table('social_tokens')
    with op.batch_alter_table('pipeline_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_sessions_user_id'))

    op.drop_table('pipeline_sessions')
    with op.batch_alter_table('monitored_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_profiles_user_id'))

    op.drop_table('monitored_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
